/*
 * stex.com rest API description
 * This is API you can use to connect your application to stex.com exchange and utilize all available features. All requests should go to the https://api3.stex.com followed by the one of the endpoint described below. The enpoints placed inside the /public section do not require authentication, all others requests should be authenticated with credentials you can get in your profile at https://app.stex.com/en/profile We also have a web-socket API present that has a number of advantages and is recommended way to connect to get the updates of the trading information To test API using this tool, please specify https://apidocs.stex.com/oauth2-redirect.html as Redirect URL in your API v3 client at https://app.stex.com/en/profile/settings 
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.pseq.stex.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * CurrencyPairGroup
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-05-02T20:38:18.888Z[GMT]")public class CurrencyPairGroup {

  @JsonProperty("id")

  private Integer id = null;

  @JsonProperty("name")

  private String name = null;

  @JsonProperty("position")

  private Integer position = null;
  public CurrencyPairGroup id(Integer id) {
    this.id = id;
    return this;
  }

  

  /**
  * CurrencyPairGroup ID
  * @return id
  **/
  @Schema(description = "CurrencyPairGroup ID")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }
  public CurrencyPairGroup name(String name) {
    this.name = name;
    return this;
  }

  

  /**
  * CurrencyPairGroup name
  * @return name
  **/
  @Schema(example = "FIAT markets", description = "CurrencyPairGroup name")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  public CurrencyPairGroup position(Integer position) {
    this.position = position;
    return this;
  }

  

  /**
  * postion of the group for sorting
  * @return position
  **/
  @Schema(example = "5", description = "postion of the group for sorting")
  public Integer getPosition() {
    return position;
  }
  public void setPosition(Integer position) {
    this.position = position;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CurrencyPairGroup currencyPairGroup = (CurrencyPairGroup) o;
    return Objects.equals(this.id, currencyPairGroup.id) &&
        Objects.equals(this.name, currencyPairGroup.name) &&
        Objects.equals(this.position, currencyPairGroup.position);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, name, position);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CurrencyPairGroup {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
